

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: dev_medi-search_com
  username: 
  password:


production:
  url: <%= ENV["DATABASE_URL"] %>


